### ISSUE TITLE
RUV stream domain have changed

### ISSUE THREAD

**Issue by oskarszoon** [hauxir/istvproxy#3]
The RUV live streams seem to be running from a new domain `footprint.net` instead of `level3.net`. 

There is also some kind of unique identifier which is now part of the url, it doesnt seem to be secrity/drm related. You can actually choose whatever you want, as long as its a 40 and 10 character hex string. So maybe used for analytics/grouping?

**Comment by hauxir** [comment]
Didn't notice this issue until now, will look into it.

Edit: Not seeing that it's causing any problems yet. it still runs fine on my machine with the currently configured URL.
